// <auto-generated />
namespace vodenje_racunov.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Neki : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Neki));
        
        string IMigrationMetadata.Id
        {
            get { return "201907301653410_Neki"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
